[package]
name = "txs"
description = ""
version = "0.0.1"
edition = '2021'

[dependencies]
# Aptos dependencies
aptos-cached-packages = { git = "https://github.com/0o-de-lally/zapatos.git", branch = "vendor" }
aptos-crypto = { git = "https://github.com/0o-de-lally/zapatos.git", branch = "vendor" }
aptos-global-constants = { git = "https://github.com/0o-de-lally/zapatos.git", branch = "vendor" }
aptos-rest-client = { git = "https://github.com/0o-de-lally/zapatos.git", branch = "vendor" }
aptos-types = { git = "https://github.com/0o-de-lally/zapatos.git", branch = "vendor" }
move-core-types = { git = "https://github.com/0o-de-lally/zapatos.git", branch = "vendor" }
bcs = { git = "https://github.com/aptos-labs/bcs.git", branch = "main" }

# Libra wallet
libra-wallet = { git = "https://github.com/0o-de-lally/libra-wallet.git", branch = "main" }

anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive", "env", "suggestions"] }
ed25519-dalek-bip32 = "0.2.0"
once_cell = "1.17.1"
rand = "0.7.3"
rand_core = "0.5.1"
serde = { version = "1.0.159", features = ["derive", "rc"] }
tiny-bip39 = "0.8.2"
tokio = { version = "1.27.0", features = ["full"] }
url = { version = "2.3.1", features = ["serde"] }
toml_edit = { version = "0.19.8", features = ["serde"] }
home = "0.5.4"
hex = "0.4.3"
indoc = "2.0.1"
serde_json = "1.0.95"
colored = "2.0.0"
